import { StyleSheet } from 'react-native';
import { colors, spacing, fontSize, borderRadius } from '@/constants';

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.background },
  container: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: 80,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  header: { alignItems: 'center', gap: spacing.sm },
  emoji: { fontSize: 48 },
  title: {
    fontSize: fontSize.xl,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  section: { gap: spacing.sm },
  sectionLabel: { fontSize: fontSize.sm, fontWeight: '600', color: colors.textPrimary },
  suggestions: { flexDirection: 'row', gap: spacing.sm },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: '#FFF4EE' },
  chipText: { fontSize: fontSize.sm, color: colors.textSecondary, fontWeight: '500' },
  chipTextActive: { color: colors.primary, fontWeight: '600' },
  form: { gap: spacing.md },
  field: { gap: spacing.xs },
  label: { fontSize: fontSize.sm, fontWeight: '600', color: colors.textPrimary },
  input: {
    height: 52,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    fontSize: fontSize.md,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
  },
  inputError: { borderColor: colors.error },
  errorText: { fontSize: fontSize.xs, color: colors.error },
  row: { flexDirection: 'row', gap: spacing.md },
  zipField: { width: 100 },
  notice: {
    backgroundColor: '#FFF4EE',
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  noticeText: { fontSize: fontSize.sm, color: colors.textSecondary, lineHeight: 20 },
  continueButton: {
    height: 54,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueButtonText: {
    fontSize: fontSize.md,
    fontWeight: '700',
    color: colors.textInverse,
    letterSpacing: 0.2,
  },
  skipButton: { alignItems: 'center', paddingVertical: spacing.sm },
  skipText: { fontSize: fontSize.sm, color: colors.textSecondary },
});
